server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: peer2
    prefer-ip-address: true
